// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Author struct {
	ID   string
	Name string
	Bio  sql.NullString
}

type Book struct {
	ID          string
	AuthorsID   string
	Name        string
	Description sql.NullString
	Price       float64
}
